[package]
name = "replay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-provider.workspace = true
angstrom-types.workspace = true
clap = { workspace = true, features = ["derive"] }
eyre.workspace = true
futures.workspace = true
rand.workspace = true
reth.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
serde.workspace = true
telemetry.workspace = true
testing-tools.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

