[package]
name = "angstrom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Angstrom Sidecar implementation
"""

[dependencies]
alloy.workspace = true
alloy-chains.workspace = true
alloy-primitives.workspace = true
angstrom-amm-quoter.workspace = true
angstrom-eth.workspace = true
angstrom-metrics.workspace = true
angstrom-network.workspace = true
angstrom-rpc.workspace = true
angstrom-types.workspace = true
clap.workspace = true
consensus.workspace = true
eyre.workspace = true
futures.workspace = true
hsm-signer.workspace = true
matching-engine.workspace = true
order-pool.workspace = true
parking_lot.workspace = true
rayon = "1"
reth.workspace = true
reth-db.workspace = true
reth-metrics.workspace = true
reth-network.workspace = true
reth-node-builder.workspace = true
reth-node-ethereum.workspace = true
reth-provider.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
uniswap-v4.workspace = true
url.workspace = true
validation.workspace = true

[target.'cfg(unix)'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]
jemalloc-prof = ["jemalloc", "tikv-jemallocator?/profiling"]

[[bin]]
name = "angstrom"
path = "src/main.rs"
